//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.ORDERS = new HashSet<ORDER>();
        }
    
        public int C_CUSTKEY { get; set; }
        public string C_NAME { get; set; }
        public string C_ADDRESS { get; set; }
        public int C_NATIONKEY { get; set; }
        public string C_PHONE { get; set; }
        public decimal C_ACCTBAL { get; set; }
        public string C_MKTSEGMENT { get; set; }
        public string C_COMMENT { get; set; }
    
        public virtual NATION NATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERS { get; set; }
    }
}
