//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINEITEM
    {
        public int L_ORDERKEY { get; set; }
        public int L_PARTKEY { get; set; }
        public int L_SUPPKEY { get; set; }
        public int L_LINENUMBER { get; set; }
        public decimal L_QUANTITY { get; set; }
        public decimal L_EXTENDEDPRICE { get; set; }
        public decimal L_DISCOUNT { get; set; }
        public decimal L_TAX { get; set; }
        public string L_RETURNFLAG { get; set; }
        public string L_LINESTATUS { get; set; }
        public System.DateTime L_SHIPDATE { get; set; }
        public System.DateTime L_COMMITDATE { get; set; }
        public System.DateTime L_RECEIPTDATE { get; set; }
        public string L_SHIPINSTRUCT { get; set; }
        public string L_SHIPMODE { get; set; }
        public string L_COMMENT { get; set; }
    }
}
