//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PART()
        {
            this.PARTSUPPs = new HashSet<PARTSUPP>();
        }
    
        public int P_PARTKEY { get; set; }
        public string P_NAME { get; set; }
        public string P_MFGR { get; set; }
        public string P_BRAND { get; set; }
        public string P_TYPE { get; set; }
        public int P_SIZE { get; set; }
        public string P_CONTAINER { get; set; }
        public decimal P_RETAILPRICE { get; set; }
        public string P_COMMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTSUPP> PARTSUPPs { get; set; }
    }
}
