//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPPLIER()
        {
            this.PARTSUPPs = new HashSet<PARTSUPP>();
        }
    
        public int S_SUPPKEY { get; set; }
        public string S_NAME { get; set; }
        public string S_ADDRESS { get; set; }
        public int S_NATIONKEY { get; set; }
        public string S_PHONE { get; set; }
        public decimal S_ACCTBAL { get; set; }
        public string S_COMMENT { get; set; }
    
        public virtual NATION NATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTSUPP> PARTSUPPs { get; set; }
    }
}
