CREATE NONCLUSTERED INDEX [L_RECEIPTDATE__L_SUPPKEY__L_ORDERKEY__L_COMMITDATE] ON [dbo].[LINEITEM]
(
	[L_RECEIPTDATE] ASC,
	[L_SUPPKEY] ASC,
	[L_ORDERKEY] ASC,
	[L_COMMITDATE] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
