CREATE NONCLUSTERED INDEX [L_PARTKEY__L_SUPPKEY__L_ORDERKEY__L_LINENUMBER__L_SHIPDATE] ON [dbo].[LINEITEM]
(
	[L_PARTKEY] ASC,
	[L_SUPPKEY] ASC,
	[L_ORDERKEY] ASC,
	[L_LINENUMBER] ASC,
	[L_SHIPDATE] ASC
)
INCLUDE ( 	[L_QUANTITY]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
