SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [L_RETURNFLAG__L_ORDERKEY] ON [dbo].[LINEITEM]
(
	[L_RETURNFLAG] ASC,
	[L_ORDERKEY] ASC
)
INCLUDE ( 	[L_EXTENDEDPRICE],
	[L_DISCOUNT]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
