CREATE NONCLUSTERED INDEX [O_ORDERDATE__O_ORDERKEY__O_CUSTKEY] ON [dbo].[ORDERS]
(
	[O_ORDERDATE] ASC,
	[O_ORDERKEY] ASC,
	[O_CUSTKEY] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
